name: build

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      test_timeout:
        required: false
        type: string
        default: 5m
    secrets:
      gh_pat:
        required: false
      codecov_token:
        required: true
      sonar_token:
        required: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/asphaltbuffet".insteadOf "https://github.com/asphaltbuffet"
        if: env.GH_PAT != null
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - name: Test
        run: go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -timeout ${{ inputs.test_timeout }}
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.os }}
          path: bin
      - name: Upload code coverage results to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./bin/coverage.out
          flags: ${{ runner.os }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
