name: snapshot

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      upload_artifact:
        required: false
        type: boolean
        default: true
    secrets:
      goreleaser_key:
        required: true
      gh_pat:
        required: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/asphaltbuffet".insteadOf "https://github.com/asphaltbuffet"
        if: env.GH_PAT != null
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --clean --snapshot --skip=sign,sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 7
          name: dist
          path: |
            dist
